#!/bin/bash
set -e

CONFIG=/opt/kubernetes-ui/kubernetes-ui/www/app/assets/js/app.js

sed -i 's|ENV_K8S_API_SERVER|'"$ENV_K8S_API_SERVER"'|g' $CONFIG
sed -i 's|ENV_K8S_DATA_SERVER|'"$ENV_K8S_DATA_SERVER"'|g' $CONFIG
sed -i 's|ENV_K8S_DATA_POLL_MIN_INTERVAL_SEC|'"$ENV_K8S_DATA_POLL_MIN_INTERVAL_SEC"'|g' $CONFIG
sed -i 's|ENV_K8S_DATA_POLL_MAX_INTERVAL_SEC|'"$ENV_K8S_DATA_POLL_MAX_INTERVAL_SEC"'|g' $CONFIG
sed -i 's|ENV_K8S_DATA_POLL_ERROR_THRESHOLD|'"$ENV_K8S_DATA_POLL_ERROR_THRESHOLD"'|g' $CONFIG
sed -i 's|ENV_C_ADVISOR_PROXY|'"$ENV_C_ADVISOR_PROXY"'|g' $CONFIG
sed -i 's|ENV_C_ADVISOR_PORT|'"$ENV_C_ADVISOR_PORT"'|g' $CONFIG

printenv
exec "$@"
